### ISSUE TITLE
beego 的controller的Abort函数，在Prepare里为啥不能显示ErrorController定义的方法呢？

### ISSUE THREAD

**Issue by kljyrx** [beego/beego#2677]
1，beego 1.8.4
2，ubuntu 16.04
请教一下，beego 的controller的Abort函数，在Prepare里为啥不能显示ErrorController定义的方法呢？
但是在controller的其他方法里使用没有问题。
例如：
func (self *IndexHandler) List() {
     self.Abort("403")//可以正常显示错误界面
}

func (self *BaseHandler) Prepare() {
     self.Abort("403")//不能正常显示错误界面
}

输出信息是
```
2017/05/26 16:42:48 [server.go:2315] [HTTP] http: panic serving [::1]:53854: 403
goroutine 100 [running]:
net/http.(*conn).serve.func1(0xc420342a80)
	/usr/local/go/src/net/http/server.go:1491 +0x12a
panic(0x553ba0, 0xc4201898a0)
	/usr/local/go/src/runtime/panic.go:458 +0x243
github.com/astaxie/beego.(*Controller).CustomAbort(0xc42038f0f8, 0x193, 0x617b57, 0x3)
	/Users/shaopengcheng/go/src/github.com/astaxie/beego/controller.go:271 +0xbe
github.com/astaxie/beego.(*Controller).Abort(0xc42038f0f8, 0x617b57, 0x3)
	/Users/shaopengcheng/go/src/github.com/astaxie/beego/controller.go:263 +0x72
lib.(*BaseHandler).NestPrepare(0xc42038f0e0)
	/Users/shaopengcheng/workspace_go/src/bbs/src/lib/Handler.go:213 +0x253
lib.(*BaseHandler).Prepare(0xc42038f0e0)
	/Users/shaopengcheng/workspace_go/src/bbs/src/lib/Handler.go:202 +0xa07
github.com/astaxie/beego.executeError(0xc420291b60, 0xc420017f80, 0x193)
	/Users/shaopengcheng/go/src/github.com/astaxie/beego/error.go:435 +0x249
github.com/astaxie/beego.exception(0xc420189240, 0x3, 0xc420017f80)
	/Users/shaopengcheng/go/src/github.com/astaxie/beego/error.go:408 +0x1e7
github.com/astaxie/beego.recoverPanic(0xc420017f80)
	/Users/shaopengcheng/go/src/github.com/astaxie/beego/config.go:162 +0x7de
panic(0x553ba0, 0xc420189220)
	/usr/local/go/src/runtime/panic.go:458 +0x243
github.com/astaxie/beego.(*Controller).CustomAbort(0xc4200d8d98, 0x193, 0x617b57, 0x3)
	/Users/shaopengcheng/go/src/github.com/astaxie/beego/controller.go:271 +0xbe
github.com/astaxie/beego.(*Controller).Abort(0xc4200d8d98, 0x617b57, 0x3)
	/Users/shaopengcheng/go/src/github.com/astaxie/beego/controller.go:263 +0x72
lib.(*BaseHandler).NestPrepare(0xc4200d8d80)
	/Users/shaopengcheng/workspace_go/src/bbs/src/lib/Handler.go:213 +0x253
lib.(*BaseHandler).Prepare(0xc4200d8d80)
	/Users/shaopengcheng/workspace_go/src/bbs/src/lib/Handler.go:202 +0xa07
github.com/astaxie/beego.(*ControllerRegister).ServeHTTP(0xc420123ce0, 0x8b3360, 0xc42024ad00, 0xc4200ce0f0)
	/Users/shaopengcheng/go/src/github.com/astaxie/beego/router.go:768 +0x1ca5
net/http.serverHandler.ServeHTTP(0xc42008a300, 0x8b3360, 0xc42024ad00, 0xc4200ce0f0)
	/usr/local/go/src/net/http/server.go:2202 +0x7d
net/http.(*conn).serve(0xc420342a80, 0x8b3ce0, 0xc420354500)
	/usr/local/go/src/net/http/server.go:1579 +0x4b7
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2293 +0x44d
2017/05/26 16:42:53 [server.go:2315] [HTTP] http: panic serving [::1]:53879: 403
goroutine 97 [running]:
net/http.(*conn).serve.func1(0xc420452f80)
	/usr/local/go/src/net/http/server.go:1491 +0x12a
panic(0x553ba0, 0xc4201e2380)
	/usr/local/go/src/runtime/panic.go:458 +0x243
github.com/astaxie/beego.(*Controller).CustomAbort(0xc4200d9218, 0x193, 0x617b57, 0x3)
	/Users/shaopengcheng/go/src/github.com/astaxie/beego/controller.go:271 +0xbe
github.com/astaxie/beego.(*Controller).Abort(0xc4200d9218, 0x617b57, 0x3)
	/Users/shaopengcheng/go/src/github.com/astaxie/beego/controller.go:263 +0x72
lib.(*BaseHandler).NestPrepare(0xc4200d9200)
	/Users/shaopengcheng/workspace_go/src/bbs/src/lib/Handler.go:213 +0x253
lib.(*BaseHandler).Prepare(0xc4200d9200)
	/Users/shaopengcheng/workspace_go/src/bbs/src/lib/Handler.go:202 +0xa07
github.com/astaxie/beego.executeError(0xc420291b60, 0xc4200177d0, 0x193)
	/Users/shaopengcheng/go/src/github.com/astaxie/beego/error.go:435 +0x249
github.com/astaxie/beego.exception(0xc42015f00b, 0x3, 0xc4200177d0)
	/Users/shaopengcheng/go/src/github.com/astaxie/beego/error.go:408 +0x1e7
github.com/astaxie/beego.recoverPanic(0xc4200177d0)
	/Users/shaopengcheng/go/src/github.com/astaxie/beego/config.go:162 +0x7de
panic(0x553ba0, 0xc42015f110)
	/usr/local/go/src/runtime/panic.go:458 +0x243
github.com/astaxie/beego.(*Controller).CustomAbort(0xc42038f458, 0x193, 0x617b57, 0x3)
	/Users/shaopengcheng/go/src/github.com/astaxie/beego/controller.go:271 +0xbe
github.com/astaxie/beego.(*Controller).Abort(0xc42038f458, 0x617b57, 0x3)
	/Users/shaopengcheng/go/src/github.com/astaxie/beego/controller.go:263 +0x72
lib.(*BaseHandler).NestPrepare(0xc42038f440)
	/Users/shaopengcheng/workspace_go/src/bbs/src/lib/Handler.go:213 +0x253
lib.(*BaseHandler).Prepare(0xc42038f440)
	/Users/shaopengcheng/workspace_go/src/bbs/src/lib/Handler.go:202 +0xa07
github.com/astaxie/beego.(*ControllerRegister).ServeHTTP(0xc420123ce0, 0x8b3360, 0xc42045a750, 0xc4204620f0)
	/Users/shaopengcheng/go/src/github.com/astaxie/beego/router.go:768 +0x1ca5
net/http.serverHandler.ServeHTTP(0xc42008a300, 0x8b3360, 0xc42045a750, 0xc4204620f0)
	/usr/local/go/src/net/http/server.go:2202 +0x7d
net/http.(*conn).serve(0xc420452f80, 0x8b3ce0, 0xc42044d840)
	/usr/local/go/src/net/http/server.go:1579 +0x4b7
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2293 +0x44d
```

错误方法配置如下：
```
func (self *ErrorHandler) Error403() {

		self.Data["PageTitle"] = "您没有权限 - " + beego.AppConfig.String("appname")
		self.Data["CurrentCid"] = 0
		self.Data["title"] = "您没有权限查看这个页面！"
		self.Data["body"] = "您没有权限查看这个页面，赶快返回首页"
		self.Layout = "layout/layout.tpl"
		self.TplName = "success.tpl"

}
```

**Comment by JessonChan** [comment]
Prepare 是beego中的保留函数，改个名字

**Comment by skyqinsc** [comment]
同问这个问题，@ @kljyrx  你的问题是应该abort会触发Panic，然后recover过程中又会执行prepare然后又panic。

so 想问， recover后为什么要执行prepare？ @huacnlee @kioopi @tmc

**Comment by gadelkareem** [comment]
I have the same problem. The Abort() function checks for the ErrorMaps but it cannot show the error page from the ErrorController. I am not 100% sure but it think that the ErrorController is not loaded yet.
