### ISSUE TITLE
validation  error:  fatal error: concurrent map read and map write

### ISSUE THREAD

**Issue by jeevi-cao** [beego/beego#4326]
验证模块在高并发下请求中插入自定义函数会出现 concurrent map read and map write

1.  未使用beego 只使用验证模块和gin集成

2. go版本

```
 GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/root/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build812165697=/tmp/go-build -gno-record-gcc-switches"
```

3. 代码gin的对应handler中添加自定义验证函数并验证 代码如下:
```
func BatchReadImage(c *gin.Context) {
	ids := c.Query("ids")
	requestId, ctx, cancel := ContextWithRequestId(c)
	defer cancel()
	logger := app.App.GetLogger().WithField("requestId", requestId)

	//校验id是否存在
	valid := validation.Validation{}
	//检验合法性  添加自定义函数
	_ = validation.AddCustomFunc("CheckIds", func(v *validation.Validation, obj interface{}, key string) {
		ids, ok := obj.(string)
		if !ok {
			_ = v.SetError(key, "type is not string")
			return
		}
		idArr := strings.Split(strings.TrimSpace(ids), ",")

		if len(idArr) < 1 {
			_ = v.SetError(key, "has no legal id")
			return
		}

		for _, ele := range idArr {
			if len(ele) < 8 {
				_ = v.SetError(key, "has illegal id")
				return
			}
		}
	})

	imgIds := ImageIds{Ids: ids}

	locationResponse := response.BatchImageLocationResponse{}
	locationResponse.RequestId = requestId
	locationResponse.CurrentTime = time.Now().Format("2006-01-02 15:04:05")
        // -- 验证
	if b, err := valid.Valid(imgIds); b != true || err != nil {
		locationResponse.Code = response.CodeMissIdParameter
		locationResponse.Status = response.StatusMissIdParameter
		msg := ""
		for _, err := range valid.Errors {
			msg += fmt.Sprintf(" %s:%s", err.Key, err.Message)
		}
		locationResponse.Reason = msg
		logger.Errorf("batch read-image request params error: %s", msg)
		c.JSON(200, locationResponse)
		return
	}

```

4. What did you expect to see?
正常不应该出现panic

5. What did you see instead?
高并发下会出现: fatal error: concurrent map read and map write
报错trace:
```
fatal error: concurrent map read and map write

goroutine 1425 [running]:
runtime.throw(0xfc00a0, 0x21)
        /usr/local/go/src/runtime/panic.go:1116 +0x72 fp=0xc00056efc0 sp=0xc00056ef90 pc=0x4365b2
runtime.mapaccess2_faststr(0xec11e0, 0xc00078a600, 0xe09acc, 0x7, 0x4, 0x0)
        /usr/local/go/src/runtime/map_faststr.go:116 +0x47c fp=0xc00056f030 sp=0xc00056efc0 pc=0x414ccc
static-image-indexer/pkg/validation.trim(0xe09acc, 0x7, 0xc000d93d90, 0xc, 0xc000b9d2d0, 0x1, 0x1, 0xfa29b5, 0x1, 0x0, ...)
        /root/go/src/git.yidian-inc.com/image/static-image-indexer/pkg/validation/util.go:237 +0x9d fp=0xc00056f0d8 sp=0xc00056f030 pc=0xd8195d
static-image-indexer/pkg/validation.parseFunc(0xe09acc, 0xa, 0xe09ab7, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /root/go/src/git.yidian-inc.com/image/static-image-indexer/pkg/validation/util.go:216 +0x631 fp=0xc00056f1d8 sp=0xc00056f0d8 pc=0xd814d1
static-image-indexer/pkg/validation.getValidFuncs(0xe09ab7, 0x3, 0x0, 0x0, 0x1317520, 0xe46820, 0xe09abc, 0x24, 0x0, 0xc000d93d70, ...)
        /root/go/src/git.yidian-inc.com/image/static-image-indexer/pkg/validation/util.go:142 +0x2a9 fp=0xc00056f300 sp=0xc00056f1d8 pc=0xd80719
static-image-indexer/pkg/validation.(*Validation).Valid(0xc000c258c0, 0xec1060, 0xc000b9d2a0, 0xfb0d21, 0x13, 0xc00066ce80)
        /root/go/src/git.yidian-inc.com/image/static-image-indexer/pkg/validation/validation.go:374 +0x22e fp=0xc00056f550 sp=0xc00056f300 pc=0xd84c7e
```

主要原因是: funcs使用map 非线程安全 不能在多协程中同时添加自定义函数和访问

```
func AddCustomFunc(name string, f CustomFunc) error {
	if unFuncs[name] {
		return fmt.Errorf("invalid function name: %s", name)
	}

	funcs[name] = reflect.ValueOf(f)
	return nil
}
```
funcs 定义

```
  funcs = make(Funcs)

 type Funcs map[string]reflect.Value
```

解决办法:
1、funcs 使用线程安全map
2、业务方将定义自定义验证函数放置在协程外提前添加

**Comment by flycash** [comment]
我感觉，这个方法设计之初，是为了在应用初始化的时候，添加好校验。而不是在执行过程中反复添加。

**Comment by jeevi-cao** [comment]
我目前解决办法 用了方法2 直接在应用初始化时候添加上
