### ISSUE TITLE
Crashed when using promethues

### ISSUE THREAD

**Issue by duansz** [beego/beego#4485]
controller code like
```
package main

import (
	"github.com/beego/beego/v2/server/web"
	"github.com/beego/beego/v2/server/web/filter/prometheus"
)

type MainController struct {
	web.Controller
}

func (this *MainController) Hello() {
	this.Ctx.WriteString("hello world")
}

func main() {
	web.BConfig.Listen.EnableAdmin = true
	web.AutoRouter(&MainController{})
	fb := &prometheus.FilterChainBuilder{}
	web.InsertFilterChain("/*", fb.FilterChain)

	web.Run()
}
```

Everything is ok when visit the url "http://localhost:8080/main/hello". But when the url not routered like "http://localhost:8080/xxx" , the process crashed. 
Crash displays
```

panic: interface conversion: interface {} is nil, not string

goroutine 9 [running]:
github.com/beego/beego/v2/server/web/filter/prometheus.report(0x7d18e, 0xc0001080f0, 0xc0002829a8)
	/Users/mac/WorkSpace/gopath/pkg/mod/github.com/beego/beego/v2@v2.0.0/server/web/filter/prometheus/filter.go:84 +0x2a5
created by github.com/beego/beego/v2/server/web/filter/prometheus.(*FilterChainBuilder).FilterChain.func1
	/Users/mac/WorkSpace/gopath/pkg/mod/github.com/beego/beego/v2@v2.0.0/server/web/filter/prometheus/filter.go:56 +0xc9
```

**Comment by duansz** [comment]
fixed in master branch
