### ISSUE TITLE
Query on usage of beego 1.12 Vs beego 2.0.2

### ISSUE THREAD

**Issue by omhingmire** [beego/beego#4517]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
beego 2.0.2

2. What operating system and processor architecture are you using (`go env`)?
Linux

3. What did you do?

I have some queries/confusion on using different versions of beego. We were using beego version 1.12.2. It was working well and we delivered the code on production.  Now a new project has started and we were using the same code base of version 1.12.2 initially. But now we are trying to move to the latest beego version 2.0.2. But we are facing too many issues while porting our code and running it with 2.0.2.

First of all, I need to know can we use both versions at the same time with dependency met? Can we use old packages (version 1.12.2) also along with the new 2.0.2 or not? I was trying to keep the same old code base with beego 2.0.2.

The following error is coming while we run our base code (version 1.12.2) + few changes with beego 2.0.2. :  

```

[root@shadings1 api]# bee run
______
| ___ \
| |_/ /  ___   ___
| ___ \ / _ \ / _ \
| |_/ /|  __/|  __/
\____/  \___| \___| v2.0.2
2021/03/01 05:07:40 WARN     ▶ 0001 Running application outside of GOPATH
2021/03/01 05:07:40 INFO     ▶ 0002 Using 'api' as 'appname'
2021/03/01 05:07:40 INFO     ▶ 0003 Initializing watcher...
2021/03/01 05:07:42 SUCCESS  ▶ 0004 Built Successfully!
2021/03/01 05:07:42 INFO     ▶ 0005 Restarting 'api'...
2021/03/01 05:07:42 SUCCESS  ▶ 0006 './api' is running...
./api flag redefined: graceful
panic: ./api flag redefined: graceful

goroutine 1 [running]:
flag.(*FlagSet).Var(0xc0000c2ba0, 0xd7b660, 0x120360e, 0xc9598b, 0x8, 0xcaa642, 0x21)
	/usr/local/go/src/flag/flag.go:851 +0x485
flag.BoolVar(...)
	/usr/local/go/src/flag/flag.go:630
github.com/beego/beego/v2/server/web/grace.init.0()
	/root/kavita/HCIProject/go/pkg/mod/github.com/beego/beego/v2@v2.0.1/server/web/grace/grace.go:93 +0x7a

```

I initialized the module with `go mod init` command and then did `go install`. So now I think it fetched the dependency for 1.12.2 and 2.0.2 as well.

**Comment by flycash** [comment]
Please remove any `github/astaxie/beego` in your code and them remove this dependency in you go.mod file.
BeegoV1 and Beegov2 both define graceful flag. Only one of them is acceptable

**Comment by omhingmire** [comment]
ok..so basically we can not use BeegoV1 and Beegov2 both packages together. Is that right? Because as soon as we have some BeegoV1 dependency package used in code, go modules will fetch BeegoV1 again and the application stops compiling.

**Comment by flycash** [comment]
Yes, and we have a `adapter` package under BeegoV2, it was used to help to migrate from v1 to v2
