### ISSUE TITLE
panic: reflect: call of reflect.Value.MethodByName on zero Value

### ISSUE THREAD

**Issue by jiedongd** [beego/beego#4595]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
v2.0

4. What did you expect to see?
panic: reflect: call of reflect.Value.MethodByName on zero Value
goroutine 1 [running]:
reflect.Value.MethodByName(0x0, 0x0, 0x0, 0x1bf1c2e, 0x16, 0xc0002ade80, 0x1ab14a0, 0x7)
        C:/Program Files/Go/src/reflect/value.go:1354 +0x205
github.com/beego/beego/v2/client/orm.isApplicableTableForDB(0x0, 0x0, 0x0, 0x1be4347, 0x7, 0xc000319801)
        D:/Goland/pkg/mod/github.com/beego/beego/v2@v2.0.0/client/orm/models_utils.go:112 +0x76
github.com/beego/beego/v2/client/orm.(*commandSyncDb).Run(0xc000123ec8, 0x7, 0xc0001586c0)
        D:/Goland/pkg/mod/github.com/beego/beego/v2@v2.0.0/client/orm/cmd.go:146 +0xb58
github.com/beego/beego/v2/client/orm.RunSyncdb(0x1be4347, 0x7, 0x1be0100, 0x5, 0xc0000364b0)
        D:/Goland/pkg/mod/github.com/beego/beego/v2@v2.0.0/client/orm/cmd.go:298 +0x90
roya/roya.RegisterDB()
        D:/Goland/src/roya/roya/mysql.go:34 +0x139
roya/roya.RegisterAll()
        D:/Goland/src/roya/roya/roya.go:10 +0x2c
main.main()
        D:/Goland/src/roya/main.go:12 +0x29

你好，我在beego v2.0.0 v2.0.1以及使用了go get -u github.com/beego/beego/v2/beego@master都没解决这个问题。
看之前的issue回答里面说是使用master可以解决，但实际上并没有。
顺便请问下，什么时候会正式发布v2.0.2

**Comment by jiedongd** [comment]
go get -u github.com/beego/beego/v2@master
