### ISSUE TITLE
The webApp can not run without go environment

### ISSUE THREAD

**Issue by zhayucun** [beego/beego#4602]
alpine without go, build with beego/v2@v2.0.1

The app can run without conf/app.conf

init global config instance failed. If you donot use this, just ignore it.  open conf/app.conf: no such file or directory

http server Running on http://:8080

but I add a new config, errors occurred.

panic: err: go command required, not found: exec: "go": executable file not found in $PATH: stderr: 

goroutine 1 [running]:
github.com/beego/beego/v2/server/web.initBeforeHTTPRun.func1()
	/go/pkg/mod/github.com/beego/beego/v2@v2.0.1/server/web/beego.go:83 +0x217
sync.(*Once).doSlow(0x10a3cd8, 0xbef9b0)
	/usr/local/go/src/sync/once.go:68 +0xec
sync.(*Once).Do(...)
	/usr/local/go/src/sync/once.go:59
github.com/beego/beego/v2/server/web.initBeforeHTTPRun()
	/go/pkg/mod/github.com/beego/beego/v2@v2.0.1/server/web/beego.go:69 +0x4d
github.com/beego/beego/v2/server/web.(*HttpServer).Run(0xc0000b0b40, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/pkg/mod/github.com/beego/beego/v2@v2.0.1/server/web/server.go:85 +0x34
github.com/beego/beego/v2/server/web.Run(0x0, 0x0, 0x0)
	/go/pkg/mod/github.com/beego/beego/v2@v2.0.1/server/web/beego.go:57 +0x65
main.main()
	/usr/src/myapp/main.go:14 +0x57

The webApp can not run without go environment?

**Comment by flycash** [comment]
No, if your `runmode=dev`, Beego will do something need `go` environment support. In most cases, it will try to generate routers based on controllers' comments. So you only need to set `runmode=test` or `runmode=prod` in your configuration file.
