### ISSUE TITLE
v2.0.1 移动项目目录controllers目录，到别的目录层级下，报错

### ISSUE THREAD

**Issue by bdxing** [beego/beego#4705]
panic: err: chdir D:\codedata\golang\yile-sup\controllers: The system cannot find the file specified.: stderr: 

goroutine 1 [running]:
github.com/beego/beego/v2/server/web.initBeforeHTTPRun.func1()
	C:/Users/Administrator/go/pkg/mod/github.com/beego/beego/v2@v2.0.1/server/web/beego.go:83 +0x21f
sync.(*Once).doSlow(0x1807958, 0x1331d08)
	D:/Go/go1.16.4/src/sync/once.go:68 +0xf7
sync.(*Once).Do(...)
	D:/Go/go1.16.4/src/sync/once.go:59
github.com/beego/beego/v2/server/web.initBeforeHTTPRun()
	C:/Users/Administrator/go/pkg/mod/github.com/beego/beego/v2@v2.0.1/server/web/beego.go:69 +0x54
github.com/beego/beego/v2/server/web.(*HttpServer).Run(0xc000004b88, 0x0, 0x0, 0x0, 0x0, 0x0)
	C:/Users/Administrator/go/pkg/mod/github.com/beego/beego/v2@v2.0.1/server/web/server.go:85 +0x3b
github.com/beego/beego/v2/server/web.Run(0x0, 0x0, 0x0)
	C:/Users/Administrator/go/pkg/mod/github.com/beego/beego/v2@v2.0.1/server/web/beego.go:57 +0x6b
main.main()
	D:/codedata/golang/yile-sup/main.go:9 +0x39

我查看是hooks->registerCommentRouter模块的问题

**Comment by bdxing** [comment]
使用生产环境运行是不会使用这个模块，就没有问题
