### ISSUE TITLE
prometheus.FilterChainBuilder访问错误页面时导致崩溃无法恢复

### ISSUE THREAD

**Issue by ytd7777** [beego/beego#4789]
func report(dur time.Duration, ctx *context.Context, vec *prometheus.SummaryVec) {
	status := ctx.Output.Status
	ptn := ctx.Input.GetData("RouterPattern").(string)
	ms := dur / time.Millisecond
	vec.WithLabelValues(ptn, ctx.Input.Method(), strconv.Itoa(status), strconv.Itoa(int(ms))).Observe(float64(ms))
}
加了prometheus 中间件后，访问没有的页面的时候，beego进程直接崩掉

panic: interface conversion: interface {} is nil, not string

goroutine 145 [running]:
github.com/beego/beego/v2/server/web/filter/prometheus.report(0xf49ac, 0xc0004018f0, 0xc0000922a0)
	C:/Users/Administrator/go/pkg/mod/github.com/beego/beego/v2@v2.0.1/server/web/filter/prometheus/filter.go:84 +0x2a5
created by github.com/beego/beego/v2/server/web/filter/prometheus.(*FilterChainBuilder).FilterChain.func1
	C:/Users/Administrator/go/pkg/mod/github.com/beego/beego/v2@v2.0.1/server/web/filter/prometheus/filter.go:56 +0xcd

**Comment by flycash** [comment]
> prometheus

Do you mean how to use prometheus filter?

**Comment by flycash** [comment]
It had been fixed, please update to newest version
