### ISSUE TITLE
`fatal error: concurrent map iteration and map write` on `session.(*FileSessionStore).SessionRelease`

### ISSUE THREAD

**Issue by goldsky** [beego/beego#4842]
**English Only**. Please use English because others could join the discussion if they got similar issue!

Please answer these questions before submitting your issue. Thanks!

**1. What version of Go and beego are you using (`bee version`)?**
```
______
| ___ \
| |_/ /  ___   ___
| ___ \ / _ \ / _ \
| |_/ /|  __/|  __/
\____/  \___| \___| v1.11.0

├── Beego     : 1.12.2
├── GoVersion : go1.17.4
├── GOOS      : linux
├── GOARCH    : amd64
├── NumCPU    : 2
├── GOPATH    : /home/myproject/gopath
├── GOROOT    : /usr/local/go
├── Compiler  : gc
└── Date      : Thursday, 6 Jan 2022
```

**2. What operating system and processor architecture are you using (`go env`)?**
```
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/myproject/.cache/go-build"
GOENV="/home/myproject/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/myproject/gopath/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/myproject/gopath"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.17.4"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build2198749240=/tmp/go-build -gno-record-gcc-switches"
```

**3. What did you do?**
It happened randomly without exact trace log. 

**4. What did you expect to see?**
No fatal error.

5. What did you see instead?
```
fatal error: concurrent map iteration and map write

goroutine 10066 [running]:
runtime.throw({0xdcb444, 0xc005280610})
	/usr/local/go/src/runtime/panic.go:1198 +0x71 fp=0xc005206c28 sp=0xc005206bf8 pc=0x437351
runtime.mapiternext(0xc005280610)
	/usr/local/go/src/runtime/map.go:858 +0x4eb fp=0xc005206c98 sp=0xc005206c28 pc=0x41132b
reflect.mapiternext(0xc8c5e0)
	/usr/local/go/src/runtime/map.go:1346 +0x19 fp=0xc005206cb0 sp=0xc005206c98 pc=0x462699
reflect.Value.MapKeys({0xcbe500, 0xc00490ff50, 0xc0052805e0})
	/usr/local/go/src/reflect/value.go:1568 +0xe5 fp=0xc005206d30 sp=0xc005206cb0 pc=0x49f685
encoding/gob.(*Encoder).encodeMap(0xc0025a0320, 0xcfb7e0, {0xcbe500, 0xc00490ff50, 0x40fdac}, 0x403f92, 0xc005206e48, 0x6000000004045d4, 0x4)
	/usr/local/go/src/encoding/gob/encode.go:371 +0x1cf fp=0xc005206df0 sp=0xc005206d30 pc=0x8812cf
encoding/gob.encOpFor.func3(0xc000813cb0, 0xc0001c0b80, {0xcbe500, 0xc00490ff50, 0xc005206ef8})
	/usr/local/go/src/encoding/gob/encode.go:571 +0x185 fp=0xc005206e80 sp=0xc005206df0 pc=0x8830e5
encoding/gob.(*Encoder).encodeSingle(0xcbe500, 0xc00490ff50, 0xc000000000cbe500, {0xcbe500, 0xc00490ff50, 0xc005206f68})
	/usr/local/go/src/encoding/gob/encode.go:301 +0x219 fp=0xc005206f08 sp=0xc005206e80 pc=0x880639
encoding/gob.(*Encoder).encode(0xc0025a0320, 0xc004b53320, {0xcbe500, 0xc00490ff50, 0xc000168f80}, 0xc000168f80)
	/usr/local/go/src/encoding/gob/encode.go:703 +0x1ac fp=0xc005206fb8 sp=0xc005206f08 pc=0x8843ec
encoding/gob.(*Encoder).encodeInterface(0xc0025a0320, 0xc0025a0358, {0xcaade0, 0xc0052805f0, 0x49fc48})
	/usr/local/go/src/encoding/gob/encode.go:419 +0x5fc fp=0xc005207108 sp=0xc005206fb8 pc=0x881a7c
encoding/gob.encOpFor.func5(0x49f4ad, 0xcaade0, {0xcaade0, 0xc0052805f0, 0xdb8cc2})
	/usr/local/go/src/encoding/gob/encode.go:589 +0x116 fp=0xc005207158 sp=0xc005207108 pc=0x88a5f6
encoding/gob.encodeReflectValue(0xcbbce0, {0xcaade0, 0xc0052805f0, 0xcaade0}, 0xdf1ef8, 0x0)
	/usr/local/go/src/encoding/gob/encode.go:363 +0xbc fp=0xc0052071d0 sp=0xc005207158 pc=0x88103c
encoding/gob.(*Encoder).encodeMap(0xc0025a0320, 0xcfb7e0, {0xcbbce0, 0xc00490fe60, 0x40fdac}, 0xc005207338, 0x4100885a75, 0x47000000014b4b40, 0x2)
	/usr/local/go/src/encoding/gob/encode.go:375 +0x2e5 fp=0xc005207290 sp=0xc0052071d0 pc=0x8813e5
encoding/gob.encOpFor.func3(0xc001050150, 0xc0001c0600, {0xcbbce0, 0xc00490fe60, 0xc005207398})
	/usr/local/go/src/encoding/gob/encode.go:571 +0x185 fp=0xc005207320 sp=0xc005207290 pc=0x8830e5
encoding/gob.(*Encoder).encodeSingle(0xcbbce0, 0xc00490fe60, 0xc000168fc0, {0xcbbce0, 0xc00490fe60, 0xc005207408})
	/usr/local/go/src/encoding/gob/encode.go:301 +0x219 fp=0xc0052073a8 sp=0xc005207320 pc=0x880639
encoding/gob.(*Encoder).encode(0xc0025a0320, 0xc004b53320, {0xcbbce0, 0xc00490fe60, 0xc000168fc0}, 0xc000168fc0)
	/usr/local/go/src/encoding/gob/encode.go:703 +0x1ac fp=0xc005207458 sp=0xc0052073a8 pc=0x8843ec
encoding/gob.(*Encoder).EncodeValue(0xc0025a0320, {0xcbbce0, 0xc00490fe60, 0x38})
	/usr/local/go/src/encoding/gob/encoder.go:251 +0x42e fp=0xc005207528 sp=0xc005207458 pc=0x8856ce
encoding/gob.(*Encoder).Encode(0xc0052075a0, {0xcbbce0, 0xc00490fe60})
	/usr/local/go/src/encoding/gob/encoder.go:176 +0xa5 fp=0xc005207568 sp=0xc005207528 pc=0x8850a5
github.com/astaxie/beego/session.EncodeGob(0x706d617473656d69)
	/home/myproject/gopath/pkg/mod/github.com/astaxie/beego@v1.12.3/session/sess_utils.go:53 +0x245 fp=0xc005207610 sp=0xc005207568 pc=0x8924a5
github.com/astaxie/beego/session.(*FileSessionStore).SessionRelease(0xc0049f4120, {0x376b6d12db, 0x14b5c40})
	/home/myproject/gopath/pkg/mod/github.com/astaxie/beego@v1.12.3/session/sess_file.go:85 +0x96 fp=0xc0052076e8 sp=0xc005207610 pc=0x88e136
github.com/astaxie/beego.(*ControllerRegister).ServeHTTP.func1()
	/home/myproject/gopath/pkg/mod/github.com/astaxie/beego@v1.12.3/router.go:767 +0x36 fp=0xc005207710 sp=0xc0052076e8 pc=0x914bd6
github.com/astaxie/beego.(*ControllerRegister).ServeHTTP(0xc0000e60c0, {0xede098, 0xc0025c9880}, 0xc0051f2000)
	/home/myproject/gopath/pkg/mod/github.com/astaxie/beego@v1.12.3/router.go:975 +0xeab fp=0xc005207ac0 sp=0xc005207710 pc=0x913ccb
net/http.serverHandler.ServeHTTP({0xedc050}, {0xede098, 0xc0025c9880}, 0xc0051f2000)
	/usr/local/go/src/net/http/server.go:2879 +0x43b fp=0xc005207b80 sp=0xc005207ac0 pc=0x6bb03b
net/http.(*conn).serve(0xc002ccd180, {0xee2c78, 0xc000bd6ff0})
	/usr/local/go/src/net/http/server.go:1930 +0xb08 fp=0xc005207fb8 sp=0xc005207b80 pc=0x6b6ba8
net/http.(*Server).Serve·dwrap·87()
	/usr/local/go/src/net/http/server.go:3034 +0x2e fp=0xc005207fe0 sp=0xc005207fb8 pc=0x6bb98e
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1581 +0x1 fp=0xc005207fe8 sp=0xc005207fe0 pc=0x468881
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:3034 +0x4e8
```

**Comment by flycash** [comment]
can you provide the reproduce code?

**Comment by goldsky** [comment]
I can not.
But from the server log, it seems when a script runs `SetSession("key", value)`, the other script calls `GetSession("key")` and `DelSession("key")` in `go func()`.

**Comment by goldsky** [comment]
I'm closing this issue.

My case was passing over the map from user session to goroutine, which was not persistent.
The solution I made was changing the argument with the user's ID instead, and recreated its map from database while running inside goroutine.
