### ISSUE TITLE
在m1的mac上进行交叉编译后运行报错

### ISSUE THREAD

**Issue by hp198410** [beego/beego#4924]
在m1 pro的macbook上进行交叉编译，在linux下无法运行, 提示以下错误:
项目为空项目, 使用bee new 生成;
交叉编译命令为:  GOOS=linux GOARCH=amd64 go build -trimpath -o main main.go

localhost test # ./main 
panic: err: go command required, not found: exec: "go": executable file not found in $PATH: stderr: 

goroutine 1 [running]:
github.com/beego/beego/v2/server/web.initBeforeHTTPRun.func1()
        github.com/beego/beego/v2@v2.0.1/server/web/beego.go:83 +0x1af
sync.(*Once).doSlow(0xf8d160, 0x55)
        sync/once.go:68 +0xd2
sync.(*Once).Do(...)
        sync/once.go:59
github.com/beego/beego/v2/server/web.initBeforeHTTPRun()
        github.com/beego/beego/v2@v2.0.1/server/web/beego.go:69 +0x31
github.com/beego/beego/v2/server/web.(*HttpServer).Run(0xc00000d3e0, {0x0, 0x0}, {0x0, 0x0, 0x60})
        github.com/beego/beego/v2@v2.0.1/server/web/server.go:85 +0x53
github.com/beego/beego/v2/server/web.Run({0x0, 0x9fb640, 0xc0000001a0})
        github.com/beego/beego/v2@v2.0.1/server/web/beego.go:57 +0x55
main.main()
        ./main.go:9 +0x25

**Comment by hp198410** [comment]
已经解决，要把runmode 改成 prod
